fs_config:
    autofield:
        update_frequency: 10
    gbdt:
        learning_rate: 0.1
        n_estimators: 100
        subsample: 1.0
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_depth: 3
        n_iter_no_change: 3
    lasso:
        alpha: 0.001
        fit_intercept: true
        copy_X: True
        max_iter: 1000
        tol: 0.0001
        positive: false
        selection: cyclic
    lpfs:
    no_selection:
    shark:
    sfs:
        num_batch_sampling: 100
    rf:
    xgb:
rec_config:
    mlp: